# Generated by Django 5.0.2 on 2024-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
